[phases.setup]
nixPkgs = ["python312", "ffmpeg_7-full"]

[phases.install]
command = "pip install -r requirements.txt"

[phases.build]
command = "echo 'Building the app...'"

[phases.start]
command = "gunicorn --bind 0.0.0.0:5000 create-mp3:app"
